# ReKit Plugin Configuration

# Define default messages with color codes
messages:
  regionSelectionPoint1: "&aFirst region point selected. Right-click again to complete the selection."
  regionCreated: "&aRegion created and associated with a kit."
  reloadedConfigurations: "&aConfigurations reloaded successfully."

# Define default wand item
wandItem:
  material: STICK
  display: "&bReKit Wand"
  lore:
    - "&7Right-click to select region points."

# You can add more configuration options as needed
# Example:
# someOption: value

# anotherOption:
#   subOption1: value1
#   subOption2: value2
