name: Sepd_ReKits
version: 1.0
main: dev.sepd.sepd_rekits.Sepd_ReKits
author: YourName
description: A Bukkit plugin for managing player kills and regions.

commands:
  createkit:
    description: Create a kit for a specific region.
    usage: /createkit <regionName> <kitName>
  deletekit:
    description: Delete a kit for a specific region.
    usage: /deletekit <regionName> <kitName>
  deleteregion:
    description: Delete a region.
    usage: /deleteregion <regionName>
  rekit:
    description: Main command for PlayerKillManager.
    usage: /rekit <subcommand>
    subcommands:
      createregion:
        description: Create a region.
        usage: /rekit createregion <regionName>
      getwand:
        description: Receive a wand for region selection.
        usage: /rekit getwand
      selectkit:
        description: Select a kit for a region.
        usage: /rekit selectkit <regionName> <kitName>
