name: RekitPlugin
version: 1.0.0
main: dev.sepd.rekitplugin.RekitPlugin
author: Sepd , Ammar
api: 1.20
api-version: 1.20
description: A plugin that allows players to create and manage kits and regions.

commands:
  createregion:
    description: Create a region and associate it with a kit.
    usage: /createregion <name> <kit>
  rekit:
    description: Main command for the ReKit plugin.
    usage: /rekit <wand|reload>
  kitcreate:
    description: Create a kit.
    usage: /kitcreate <kitname>
  kitselect:
    description: Select a kit for a specific region.
    usage: /kitselect <regionname> <kitname>

permissions:
  rekit.admin:
    description: Grants access to all ReKit commands.
    default: op
