# Config file for PlayerKillManager

messages:
  inventory-cleared: "&aYour inventory has been cleared."
  kit-received: "&aYou received a kit for being in region: %region%"
  no-kit-defined: "&cNo kit defined for region: %region%"
  kit-saved: "&aYour current inventory has been saved as kit '%kit%' for region: %region%"
  kit-deleted: "&aKit '%kit%' deleted for region: %region%"
  region-deleted: "&aRegion '%region%' deleted."
  region-created: "&aRegion created: %region%"
  wand-received: "&aYou received a wand!"
  wand-selection-first: "&aFirst point selected at: %location%"
  wand-selection-second: "&aSecond point selected at: %location%"

# You can add more configuration options here if needed
